# Generated by Django 3.2.20 on 2025-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('profile_image_url', models.URLField(null=True)),
                ('company', models.CharField(max_length=32, null=True, verbose_name='회사')),
                ('position', models.CharField(max_length=16, null=True, verbose_name='직책')),
                ('memo', models.TextField(null=True, verbose_name='메모')),
                ('address', models.TextField(null=True, verbose_name='주소')),
                ('birthday', models.DateField(null=True, verbose_name='생일')),
                ('website', models.CharField(max_length=256, null=True, verbose_name='웹사이트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(related_name='contacts', to='members.Label')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name'], name='members_con_name_811096_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='members_con_email_834d33_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='members_con_phone_e234d2_idx'),
        ),
    ]
